### ISSUE TITLE
Golem and BOINC

### ISSUE THREAD

**Issue by dkalaxdk** [P7-Team/P7-Report#10]
**What should be written?**
Description of Golem and BOINC, with their advantages and disadvantages.

Sub issue of #5

**Comment by AxialDark** [comment]
Reviewed Golem and BOINC sections

**Comment by soenderby** [comment]
Sections reviewed, with comments and minor edits

**Comment by soenderby** [comment]
Review number two completed. Minor corrections, and a single comment.
