### ISSUE TITLE
Summary of Distributed training of DNN's

### ISSUE THREAD

**Issue by soenderby** [P7-Team/P7-Report#14]
**What should be written?**
What exactly should this section communicate to the reader?

Describe if/how training of Deep Neural Networks is a problem that can be solved using distributed systems

Related to #6

**Comment by AxialDark** [comment]
Finished reviewing, approved with comments

**Comment by dkalaxdk** [comment]
Reviewed.

**Comment by dkalaxdk** [comment]
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue.
- [x] The section is reasonably concise and gets to the point.
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs.
- [x] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it.
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Alex review checklist
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue.
- [x] The section is reasonably concise and gets to the point.
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs.
- [x] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it.
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Moving to "Done" as none of the reviewers have left any comments in the text and all positives are checked
