### ISSUE TITLE
Alternative solutions: CLAAUDIA

### ISSUE THREAD

**Issue by AxialDark** [P7-Team/P7-Report#15]
**What should be written?**
What exactly should this section communicate to the reader?

Related to #5

**Comment by AxialDark** [comment]
Ready for review: sections/introduction/Relatedwork/clauudia

**Comment by dkalaxdk** [comment]
Reviewed.

**Comment by soenderby** [comment]
Reviewed

**Comment by dkalaxdk** [comment]
- [x] The section is relevant for the report.
      Har smidt en kommentar ang ovenstående.
- [x] It communicates and covers the information required by the issue.
- [x] The section is reasonably concise and gets to the point.
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs.
- [x] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it.
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by soenderby** [comment]
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue.
- [x] The section is reasonably concise and gets to the point.
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs.
- [x] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it.
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

Top marks :)
