### ISSUE TITLE
Distributed Problems:  Data analysis

### ISSUE THREAD

**Issue by dkalaxdk** [P7-Team/P7-Report#17]
**What should be written?**
Sub issue of #6

**Comment by dkalaxdk** [comment]
Reviewed.

**Comment by AxialDark** [comment]
Finished reviewing

**Comment by soenderby** [comment]
Second review complete. Content and structure are good, made minor changes and left comments where I believer further clarification is needed.

**Comment by AxialDark** [comment]
Alex review checklist
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue.
- [x] The section is reasonably concise and gets to the point.
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs.
- [ ] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it.
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

Could not really check the segway as it is not included in the report currently, which means i do not know which section it would be a segway of.
