### ISSUE TITLE
Introduction to initial problem (and initial problem)

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#18]
**What should be written?**

The section should communicate the reasons behind choosing the problem statement. 

The section should also present a problem statement.  

[Link for reviewers](https://www.overleaf.com/project/6141b6c00d353feabf2b4259)

**Comment by soenderby** [comment]
Reviewed, with comments.

**Comment by soenderby** [comment]
Second Review

- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue.
- [x] The section is reasonably concise and gets to the point.
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs.
- [x] There is a good segue from the previous section.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it.
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by Kaliahh** [comment]
Har omskrevet det. Fokus går væk fra e-learning og mere over på økonomi.

**Comment by MikaelVM** [comment]
@MikaelVM<br> 
- [x] The section is relevant for the report. <br> 
- [x] It communicates and covers the information required by the issue. <br> 
- [x] The section is reasonably concise and gets to the  point. <br>
- [x] There is a rød tråd. <br> 
- [x] There are no jarring jumps between paragraphs. <br> 
- [x] There is a good segue from the previous section. <br> 
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. <br> 
- [x] The sections uses the type of language agreed upon <br> 
- [x] All claims have citations, and the claims can be logically derived from those citations. <br> 
- [ ] Is there anything missing? <br>

**Comment by Kaliahh** [comment]
Der er nogle kommentarer jeg har svaret på eller lavet rettelser baseret på.
