### ISSUE TITLE
Distributed file saving

### ISSUE THREAD

**Issue by zaztz** [P7-Team/P7-Report#19]
**What should be written?**
We need research the following topics

 File storage
  -Distribudted Database
  -Distributed File system 
  -Other options  
  
What exactly should this section communicate to the reader?
 Which of the above options, we will use and why

**Comment by soenderby** [comment]
@soenderby 

- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?
