### ISSUE TITLE
Distributed Problems: Scientific Research

### ISSUE THREAD

**Issue by MikaelVM** [P7-Team/P7-Report#20]
**What should be written?**
Should give the reader an understanding of how distributed systems are used in various fields of science.

[Link to section for review](https://www.overleaf.com/project/6141b6c00d353feabf2b4259)

**Comment by MikaelVM** [comment]
Section written, not yet reviewed

**Comment by Kaliahh** [comment]
Related to #6

**Comment by dkalaxdk** [comment]
@naitoarekkus<br>
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. <br>               
- [x] The section is reasonably concise and gets to the  point. <br>                 
- [x] There is a rød tråd. <br>                 
- [x] There are no jarring jumps between paragraphs. <br>                 
- [x] There is a good segue from the previous section. <br>                 
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. <br>                 
- [x] The sections uses the type of language agreed upon <br>                 
- [x] All claims have citations, and the claims can be logically derived from those citations. <br>
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@soenderby<br> 

Reviewed twice

- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. <br>               
- [x] The section is reasonably concise and gets to the  point. <br>                 
- [x] There is a rød tråd. <br>                 
- [x] There are no jarring jumps between paragraphs. <br>                 
- [x] There is a good segue from the previous section. <br>                 
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. <br>                 
- [x] The sections uses the type of language agreed upon <br>                 
- [x] All claims have citations, and the claims can be logically derived from those citations. <br>                 
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Is in done, will close
