### ISSUE TITLE
Alternative Solutions: SheepIt

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#21]
**What should be written?**
A description of SheepIt, what they do and how they do it.

Related to #5

**Comment by dkalaxdk** [comment]
@zaztz<br> 
- [x] The section is relevant for the report. <br> 
- [x] It communicates and covers the information required by the issue. <br> 
- [x] The section is reasonably concise and gets to the  point. <br>
- [x] There is a rød tråd. <br> 
- [x] There are no jarring jumps between paragraphs. <br> 
- [x] There is a good segue from the previous section. <br> 
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. <br> 
- [x] The sections uses the type of language agreed upon <br> 
- [x] All claims have citations, and the claims can be logically derived from those citations. <br> 
- [ ] Is there anything missing? <br>

**Comment by dkalaxdk** [comment]
@MikaelVM<br> 
- [x] The section is relevant for the report. <br> 
- [x] It communicates and covers the information required by the issue. <br> 
- [x] The section is reasonably concise and gets to the  point. <br>
- [x] There is a rød tråd. <br> 
- [x] There are no jarring jumps between paragraphs. <br> 
- [x] There is a good segue from the previous section. <br> 
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. <br> 
- [x] The sections uses the type of language agreed upon <br> 
- [x] All claims have citations, and the claims can be logically derived from those citations. <br> 
- [ ] Is there anything missing? <br>
