### ISSUE TITLE
Design arkitektur (diagrammer)

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#23]
Der skal laves flere diagrammer:

- [x] Undersøg om der er en måde at lave arkitekturer på som vi kan bruge. (Vi kan bruge C4-modellen)
- [x] Find eller lav templates. (I draw.io kan man inkludere C4-model elementer)
- [x] Højt abstraktion-niveau, kig helt overordnet på det. Vi skal kunne vise hvordan vores arkitektur er scalable.
- [x] Vær opmærksom på hvad det er vi vil kommunikere med diagrammet, hvad det er for et behov vi gerne vil dække.
- [x] Det skal være klart hvad de forskellige elementer af diagrammet betyder.

Overvej om der er behov for flere diagrammer, måske også nogle der gå mere i detajle.

**Comment by AxialDark** [comment]
Drive folder with the architecture drawings can be found at this link [Archtecture Drawing Folder](https://drive.google.com/drive/folders/1Dz6NIRZNm5t1vAy9spT-D6cdnVbi9ic-?usp=sharing)

**Comment by AxialDark** [comment]
Ready for review

**Comment by dkalaxdk** [comment]
@zaztz
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue.
- [ ] The section is reasonably concise and gets to the  point. <br>                 
- [ ] There is a rød tråd. <br>                 
- [ ] There are no jarring jumps between paragraphs. <br>                 
- [ ] There is a good segue from the previous section. <br>                 
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. <br>                 
- [ ] The sections uses the type of language agreed upon <br>                 
- [ ] All claims have citations, and the claims can be logically derived from those citations. <br>                 
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@dkalaxdk <br> 
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. <br>               
- [ ] The section is reasonably concise and gets to the  point. <br>                 
- [ ] There is a rød tråd. <br>                 
- [ ] There are no jarring jumps between paragraphs. <br>                 
- [ ] There is a good segue from the previous section. <br>                 
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. <br>                 
- [ ] The sections uses the type of language agreed upon <br>                 
- [ ] All claims have citations, and the claims can be logically derived from those citations. <br>                 
- [ ] Is there anything missing?

**Comment by Kaliahh** [comment]
Reviewed by group
