### ISSUE TITLE
Beskriv arkitektur (i rapporten, med hjælp fra diagrammerne)

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#24]
#23 skal være lavet inden.

- [x] Beskriv de enkelte elementer der indgår i arkitekturen og hvordan de interagerer.
- [x] Beskriv og argumenter for hvorfor de enkelte elementer er der.

**What still needs to be argumented for**
- [x] More?

**Jakob is looking at and argumenting for**
- [x] Why ASP.NET for C#, other technologies for developing ReST API's
- [x] Choice of using HTTP and ReST for communication between server and client

**Alex is looking at and argumenting for**
- [x] Described the overall architecture described in the architecture diagrams
- [x] Argument for the usage of the C4-model for describing the architecture
- [x] Why do we have a security component? (ref to Michael' section)
- [x] Why distributed DB and why the specified type of DB? (Ref the section being written by Alexander
- [x] Why client/server model used for the communication between clients and the web-service? why not alternatives (SOA, P2P)
- [x] Why the usage of the distributed file system and why the choice of Hadoop HDFS (Ref to Christian's section, NOT IN REPORT YET!!!)

**Comment by AxialDark** [comment]
Files to review:
- sections/design/architecture/architecture_design
- sections/design/architecture/architecture_scalability
- sections/design/architecture/architecture_framework
- sections/design/architecture/architechture_client_server_communication

Potentially also check the linked sections to ensure that the relevant information is provided in the linked sections

**Comment by dkalaxdk** [comment]
@zaztz
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd. 
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
@Kaliahh 
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd. 
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?


Tænker der skal en større mere overordnet introduktion til i afsnit 3.1 og 3.2 der introducerer det der kommer, så der ikke skal være små handoffs mellem afsnit. 

Der er et jump mellem peer-to-peer og afslutningen på scalability afsnittet.

**Comment by dkalaxdk** [comment]
Har kigget på P2P igen.

**Comment by AxialDark** [comment]
Har igen kigget på:
- sections/design/architecture/architecture_design
- sections/design/architecture/architecture_scalability

**Comment by soenderby** [comment]
Har kigget på client-server og framework igen.

**Comment by dkalaxdk** [comment]
Har læst P2P færdigt.

Virker til at være done.

**Comment by AxialDark** [comment]
No more comments and no more changes, task is done
