### ISSUE TITLE
Restructure Introduction such that the problem statement is backed up by the Related Work

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#26]
The problem statement at the end of the introduction is really an initial problem. The problem statement should appear in a section presenting what this project will contribute. The structure should therefore be:

- Introduction
  - Initial Problem
- Related Work
- Problems Suitable for Distribution
- This Project's Contribution
  - Problem Statement

This way, the problem statement in This Project's Contribution will be backed up by the Related Work and Problems Suitable for Distribution, and can say specifically want we want to do using which technologies.

**Comment by dkalaxdk** [comment]
@naitoarekkus
 - [x] The section is relevant for the report. 
 - [x] It communicates and covers the information required by the issue. 
 - [x] The section is reasonably concise gets to the point. 
 - [x] There is a rød tråd. 
 - [ ] There are no jarring jumps between paragraphs. 
 NOTE: Der er nogle grimme hop imellem de store afsnit (Introduction -> Related Work, Related Work -> Problems Suitable...), men jeg har sat TODOs til at lave korte introduktioner hvor jeg mener det giver mening.
 - [ ] There is a good segue from the previous section. 
 NOTE: Denne her kommer meget af det samme som noten ovenunder, der var dog også overgangen fra Introduction til de efterfølgende afsnit hvor der ikke blev lagt op til afsnittet "Problems Suitable...", har sat en kommentar 
 - [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. 
 - [x] The sections uses the type of language agreed upon 
 - [x] All claims have citations, and the claims can logically derived from those citations. 
 - [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@dkalaxdk
 - [x] The section is relevant for the report. 
 - [x] It communicates and covers the information required by the issue. 
 - [x] The section is reasonably concise gets to the point. 
 - [x] There is a rød tråd. 
 - [ ] There are no jarring jumps between paragraphs. 
 - [x] There is a good segue from the previous section. 
 - [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it. 
 - [x] The sections uses the type of language agreed upon 
 - [x] All claims have citations, and the claims can logically derived from those citations. 
 - [ ] Is there anything missing?

**Comment by Kaliahh** [comment]
Tænker at det er fint med todos på at lave overgange. 

Jeg har lige svaret på jeres kommentarer på præsentationen af resten af rapporten i introduktionen.
