### ISSUE TITLE
Design database schemas

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#30]
Tasks:
- [x] What data should we store?
- [x] ER diagrams
- [x] Argumentation! ;)
- [x] Does the schema conform to normal form?

[Link til reviewers](https://www.overleaf.com/project/6141b6c00d353feabf2b4259)

**Comment by dkalaxdk** [comment]
@dkalaxdk
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd. 
- [x] There are no jarring jumps between paragraphs. 
   There are jumps, but can't see a way of avoiding it.
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@MikaelVM
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd. 
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
File(s) for review at: "sections/design/database/ER.tex"

**Comment by AxialDark** [comment]
@dkalaxdk @MikaelVM 
Because an error was found in the ER diagram (missing distinguisher for byzantine checking), there is also a pull request to be reviewed.
It can be found at: https://github.com/P7-Team/P7-WebService/pull/56

**Comment by AxialDark** [comment]
Everything is good, moved to Done
