### ISSUE TITLE
Ret BOINC afsnittet til

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#33]
Fokus på:
- Hvad gør de, og hvorfor?
- Hvorfor løser de ikke vores problem?
- Hvilke ideer havde de der var gode, som vi tager med videre, og hvorfor?

**Comment by dkalaxdk** [comment]
@dkalaxdk
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [ ] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@AxialDark 
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
NOTE: Tænker at den kommer efter introduktionen til afsnittet er skrevet
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@Kaliahh
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section _Not relevant in my opinion_
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?
