### ISSUE TITLE
Summary på Existing Products and Services

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#38]
Hvad tager vi med fra de produkter vi har kigget på, og hvorfor? 

Vi har også opdaget at alle eksisterende produkter og services giver adgang til mere power igennem distribuering. Det giver god mening, hvorfor? 

Vi vil kigge på hvilke typer af opgaver der får gavn af distribuering.

**Comment by soenderby** [comment]
approve

**Comment by zaztz** [comment]
approve
