### ISSUE TITLE
Ret Distributed Training of Deep Neural Networks til

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#39]
Skal omskrives så det ligner Data Analysis afsnittet. 

Hav fokus på:
- Hvad er det?
- Hvorfor fungerer det ikke på én maskine
- Hvorfor fungerer det bedre på flere maskiner?
- Hvad tager vi med fra vores undersøgelse af dette problem / Hvad har vi lært?

**Comment by dkalaxdk** [comment]
@zaztz
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [x] Is there anything missing?

**Comment by dkalaxdk** [comment]
@soenderby
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [ ] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@AxialDark
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
NOTE: Tror det eneste der mangler er at der kommer en overordnet introduction til det overordnede afsnit og den forrige section bliver rettet til.
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Looks good

**Comment by zaztz** [comment]
Det ser fint ud
