### ISSUE TITLE
Ret Rendering til

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#40]
Skal omskrives så det ligner Data Analysis afsnittet. 

Hav fokus på:
- Hvad er det?
- Hvorfor fungerer det ikke på én maskine
- Hvorfor fungerer det bedre på flere maskiner?
- Hvad tager vi med fra vores undersøgelse af dette problem / Hvad har vi lært?

**Comment by dkalaxdk** [comment]
@soenderby
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [ ] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@AxialDark
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
NOTE: Technically speaking the quesion "Hvorfor fungere det ikke på en maskine?" is not answered, but the question itself does not really make sense to me.
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@dkalaxdk
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?
