### ISSUE TITLE
Add subsection Map-Reduce under Scientific Research

### ISSUE THREAD

**Issue by MikaelVM** [P7-Team/P7-Report#41]
Overvej hvordan todo'en "Eventuelt skrive det om baseret på feedback fra vejleder" kan løses også.

Fokus på hvordan Map-Reduce bliver brugt indenfor videnskabelige artikler. Eventuelt kig på simulation af universet

**Comment by Kaliahh** [comment]
Ane
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
@AxialDark 
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?
