### ISSUE TITLE
Summary af Problems Suitable for Distribution

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#42]
Beskriv at vi har etableret behovet og interessen for at løse problemer distribueret.

Der er forskellige måder at håndtere distribueringen på: På nogle måder kan computerne snakke sammen, på andre er de isolerede og arbejder med det de fik som input. 

Vi vælger dem der kører isoleret (Ikke får kontinuert input eller kommunikere med andre nodes), hvorfor?

**Comment by AxialDark** [comment]
Review of files: "sections/introduction/Relatedwork/summary"

**Comment by AxialDark** [comment]
Dette er en første udgave

**Comment by soenderby** [comment]
Approve

**Comment by AxialDark** [comment]
Fixed
