### ISSUE TITLE
This Project's Contribution

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#43]
Opsummering på eksisterende produkter + problemer der gavner af distribuering:
- Der findes ikke eksisterende produker / services der løser problemet.
- Distribuering er en god måde at få mere kraft på, men det afgrænser os fra opgaver der ikke kan parallelliseres. Den eneste løsning på at klare opgaver der ikke kan parallelliseres er også bare at købe en hurtigere computer, hvilket ikke er et interssant problem. 
- Af de problemer der får gavn af distribuering, har vi valgt at fokusere på dem der kører isoleret. 

Vores contribution bliver så at lave en service der distribuerer opgaverne, og som opfylder kravene i Requirement

Endeligt definere de ord vi bruger (requester, provider). I de foregående afsnit bruges produktets / servicens egne termer

**Comment by dkalaxdk** [comment]
@AxialDark
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@dkalaxdk
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

Der er lidt kommentare vedrørende formuleringer, men ellers ser det fint ud.

**Comment by soenderby** [comment]
First draft, jeg vil foreslå at fokusere hovedsagligt på struktur og indhold.
