### ISSUE TITLE
Requirements - User Stories

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#44]
Hent dem ud fra Product Backloggen. Kun titler. Eventuelt ret titler til hvis de ikke er gode nok.

Prioriter i must have, should have, could have og nice to have. 

En beskrivelse af de forskellige prioriteringer. Altså f.eks. hvorfor er dem der er prioriteret til must have prioriteret til must have? Hvad har vi når vi har opfyldt hver kategori?

Vores MVP er det der er i must have.

**Comment by AxialDark** [comment]
@AxialDark
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
NOTE: Skal ikke kunne sige, introduktionen til afsnittet er ikke skrevet endnu
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by Kaliahh** [comment]
@soenderby 
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section  
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?
