### ISSUE TITLE
Requirements - Technical Requirements

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#45]
Vi skal have requirements inden for:
- Sikkerhed (login, docker)
- Performance (request håndtering) (scalability)
- Fault tolerance (replication, byzantine) (scalability)

Find gerne på flere selv.

Prioriter i must have, should have, could have og nice to have. 

En beskrivelse af de forskellige prioriteringer. Altså f.eks. hvorfor er dem der er prioriteret til must have prioriteret til must have? Hvad har vi når vi har opfyldt hver kategori?

Vores MVP er det der er i must have.

**Comment by dkalaxdk** [comment]
@AxialDark 
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
NOTE: I have made some comments, there are some explanations which could benefit from further explanations
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@Kaliahh
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?
