### ISSUE TITLE
Introduction - Development process

### ISSUE THREAD

**Issue by AxialDark** [P7-Team/P7-Report#47]
**What should be written?**
What development process have we used?
Why have we choosen this process?
What changes have we made to better fit the project

**Comment by AxialDark** [comment]
Review at: sections/introduction/process

**Comment by dkalaxdk** [comment]
@zaztz
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- Synes der er en mangle på beskrivelse af vores review processer samt at vi valget at bruge userstorys  
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- Denne section virker som den ikke relation til de tidligere sectioner og den som kommer efter den.  Derfor vil jeg foreslå at den bliver flytte frem eller tilbage. 
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@AxialDark
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [ ] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by dkalaxdk** [comment]
@dkalaxdk
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Fixed
