### ISSUE TITLE
Related Work: Alternative solutions

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#5]
**What should be written?**
What exactly should this section communicate to the reader?

Description of the alternative solutions that already exist, what their limitations are, and how they are set up (architecture)

**Sub tasks**
- [x] #10 
- [x] #12 
- [x] #13 
- [x] #15 
- [x] #16 
- [x] #21

**Comment by AxialDark** [comment]
Sections ready for review:
| Sections | Overleaf Files |
| --------- | ----- |
| 1.2.3  Entropia | {sections/introduction/Relatedwork/entropia} |
| 1.2.4  Supercomputers | {sections/introduction/Relatedwork/supercomputers_general} |
| 1.2.5  CLAAUDIA | {sections/introduction/Relatedwork/clauudia} |
| 1.2.6  Distributed Service Oriented Architecture | {sections/introduction/Relatedwork/distributed_service_oriented_architecture} |

**Comment by AxialDark** [comment]
Har reviewet Alexanders afsnit omkring Golem og BOINC
