### ISSUE TITLE
Go through Design chapter, and make sure it relates to the requirements

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#50]
Each section should relate to one or more requirement. It should be desribed how they fulfill the requirement

**Comment by dkalaxdk** [comment]
Updated stuff in:
 - Scheduler
 - File System
 - Database
 - Security
 
Kunne ikke finde ud af om det var relevant i:
- Architecture
- Using HTTP for Client-Server Communication

**Comment by AxialDark** [comment]
@AxialDark 
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [ ] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by Kaliahh** [comment]
- [x] Scheduler
 - [x] File System
 - [x] Database
 - [x] Security

**Comment by AxialDark** [comment]
- [x] Scheduler
 - [x] File System
 - [x] Database
 - [x] Security
