### ISSUE TITLE
We need to talk about quality of service, and how we do it, somewhere. 

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#52]
We might just have to say that we use Digital Ocean, and use their stuff, at least for availability

**Comment by AxialDark** [comment]
Review file: "sections/evaluation/quality_of_service"

**Comment by AxialDark** [comment]
@dkalaxdk 

- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Ane

- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section _Ikke relevant efter min mening_
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Reviews fixed, done
