### ISSUE TITLE
Define the narrative flow of the Implementation chapter

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#53]
Make section, write notes to guide the writer.

Make issues for the sections 

Do this with someone

**Derived Issues:**
- [x] #67
- [x] #62 
- [x] #63
- [x] #64
- [x] #65
- [ ] #66

**Comment by AxialDark** [comment]
Narative reviewed by the group, seems ok

**Comment by AxialDark** [comment]
Reviewers of this task should check the description of the derived tasks to make sure that they are descriptive enough

**Comment by AxialDark** [comment]
It looks ok
