### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#60]
Write about the process in each of the following sections:

- [x] Introduction 
- [x] Implementation (TDD)
- [x] Evaluation (Usability testing) (Impossible, as we have not done them)
- [x] Our Process 
  - [x] Opsummering, andre tanker? 
  - [x] Kig på vores review og retrospective dokumenter, tag ting med fra det. 
  - [x] Hvordan brugte vi Scrum?
  - [x] Hvordan gik det med vores sprints?
  - [x] Hvad skete der i dem? 
  - [x] Tal her om vores definition of done og vores review proces

**Comment by AxialDark** [comment]
Files to review list:
- sections/introduction/process_introduction
- sections/implementation/process_tdd
- sections/discussion/process

**Comment by AxialDark** [comment]
@soenderby 

- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Ane
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
Yeeeeeassssssh!
