### ISSUE TITLE
Describe core functionality of the web service implementation

### ISSUE THREAD

**Issue by AxialDark** [P7-Team/P7-Report#62]
This section should describe the implementation of the core functionality of the web service.
The core functionalities are the "scheduler" implementation and the "automater" class which drives it.

This section should include a interface UML diagram which shows how the different interfaces "calls" or "interacts" with each other.
It should be kept at an interface level to make the diagram more manageable and easier to explain (this means that classes implementing the interfaces should not be present).

The diagram is then used to explain the link between the interfaces and which technical requirements (ref) that they fulfil.
This is of course only when relevant for the interface/requirement, sometimes it could make sense to ref to an earlier section of the report (maybe for DB interactions and the DB design section).

**Comment by AxialDark** [comment]
@AxialDark 
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by zaztz** [comment]
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd. \n 
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [ ] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by zaztz** [comment]
- [x] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd. \n 
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?
