### ISSUE TITLE
Describe how communication is handled/implemented in the web service

### ISSUE THREAD

**Issue by AxialDark** [P7-Team/P7-Report#64]
This section follows #63 , which should end by describing how data is stored on the web service.

This section should then explain the use of the ASP.NET framework to handle communication to and from the web service.
This is through the definition of controllers (and how ASP.NET maps the controller methods to endpoints) and how the information from requests are mapped to C# objects using ASP.NET attributes to handle this ([FromBody], [FormFiles], etc.)

**Comment by soenderby** [comment]
@soenderby

- [x] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
      NOTE: Model binding ved brug af [FromBody] og [FromForm] osv. er ikke beskrevet
- [ ] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [x] Is there anything missing?

**Comment by zaztz** [comment]
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd. \n 
- [x] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by MikaelVM** [comment]
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
      NOTE: Model binding ved brug af [FromBody] og [FromForm] osv. er ikke beskrevet
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [x] Is there anything missing?
