### ISSUE TITLE
Describe how the communication from the client to the web service is presented to the user (UI)

### ISSUE THREAD

**Issue by AxialDark** [P7-Team/P7-Report#65]
This section follows #64 which ends by descriping how communication is received on the web service using the ASP.NET framework.

This section should communicate how the users communicate with the web service using the UI.
This should then lead into the use of the Model View View Model design pattern (MVVM) in implementing the UI and explain why the implemented UI does not look like the described design, which should be in the in the Design chapter by issue #48 .

Finish the section off by explaining that the implemented client is just to show how a custom client can be implemented to communicate with the web service

**Comment by soenderby** [comment]
@soenderby 

- [x] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
       NOTE: Det er kortfattet, men pointen mangler
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [x] Is there anything missing?

I starten af afsnittet nævnes det at clienten kan bruges til at teste servicen. Denne pointe skal gerne samles op igen i teksten. Hvilke komponenter er med til at gøre dette og hvordan?  
I afsnittet udpeges og forklares nogle detaljer.   
Hvad jeg mangler er formålet med disse detaljer, hvad er det vi vil vise læseren med dem?
