### ISSUE TITLE
Update Architecture scalability

### ISSUE THREAD

**Issue by dkalaxdk** [P7-Team/P7-Report#72]
- [x] Define our definition of scalability in "Architecture Scalability" 
Alex har lavet en kommentar, giv den et kig.
Linje 12 da denne issue blev lavet.

- [x] Fix reference to DSOA as it does not exists, potentially re-write to get around this ref.

**Comment by AxialDark** [comment]
@zaztz 
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [x] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
@Second
- [ ] The section is relevant for the report.
- [ ] It communicates and covers the information required by the issue. 
- [ ] The section is reasonably concise and gets to the point. 
- [ ] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [ ] There is a good segue from the previous section
- [ ] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [ ] The sections uses the type of language agreed upon
- [ ] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
rettelser er lavet i: "sections/design/architecture/architecture_scalability"
Under afsnit:
- Scalability of SOA
- Scalability of Microservices
- Architecture Scalability (definition af scalability

**Comment by AxialDark** [comment]
Fixed
