### ISSUE TITLE
Discuss Implementation

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#75]
Filen er sections/discussion/implementation

- [x] Dan dig et overblik over hvad der skal diskuteres. 
- [x] Skriv det ;)

Der er noter i selve filen. De er muligvis ikke dækkende.

**Comment by soenderby** [comment]
Pointerne i afsnittet er at vi opdelte udviklingen for at kunne udnytte alle udviklere, men fordi vi ikke havde en fælles forståelse resulterede det i at komponenterne alligvel skulle ændres når vi satte dem sammen.
TDD var godt, da det gav os regression tests til disse ændringer, men testene skulle også veligeholdes når der blev foretaget ændringer.

Konklusionen er mere eller mindre at skyde skylden for alle de dårlige ting på vores development process, som diskuteres i det efterfølgende afsnit.

Jeg har gjort mig nogle tanker om effekten af vores proces på implementationene i kommentarer i bunden af overleaf dokumentet.

**Comment by Kaliahh** [comment]
Ane
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs. 
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?

**Comment by AxialDark** [comment]
@AxialDark 
- [x] The section is relevant for the report.
- [x] It communicates and covers the information required by the issue. 
- [x] The section is reasonably concise and gets to the point. 
- [x] There is a rød tråd.
- [ ] There are no jarring jumps between paragraphs.
NOTE: Vil tro at det kan klares med sen subsection header. Er kommet med nogle foreslag (siger ikke at de er gode)
- [x] There is a good segue from the previous section
- [x] The section is written in such a way that a new reader, who has read the report up until the section, would understand it
- [x] The sections uses the type of language agreed upon
- [x] All claims have citations, and the claims can be logically derived from those citations.
- [ ] Is there anything missing?
