### ISSUE TITLE
Omstrukturer Database afsnittet

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#78]
Beskriv data udledt fra vores requirements (De siger vi skal have batches, tasks, osv. Hvilken data kan vi udlede af dem? Hvad kan vi også udlede som ikke står der eksplicit? F.eks. filer til at gemme ting).

Diskuter om vi skal bruge NoSQL eller relationel ud fra dataen. 

Vi skal vælge en DBMS, den skal kunne distribueres og have replikation. Vi vælger MySQL.

Design strukturen af databasen (ER diagrammer).

Oversæt til relationel model.

**Comment by dkalaxdk** [comment]
Har været igennem den del jeg skrev.

**Comment by AxialDark** [comment]
Har været igennem den del som jeg skrev

**Comment by dkalaxdk** [comment]
Did a read again.

**Comment by AxialDark** [comment]
Har været igennem igen
