### ISSUE TITLE
Investigate current architecture to find potential bottlenecks in the scaling

### ISSUE THREAD

**Issue by AxialDark** [P7-Team/P7-Report#8]
**What should be written?**
What exactly should this section communicate to the reader?

What is our current architecture?
Why have we designed the architecture this way?
What are the potential bottlenecks when the service is scaled up?
How can we mitigate the bottlenecks?

**When is research done?**
When documentation is found for how to mitigate the most servere bottlenecks in the architecture?

**Comment by dkalaxdk** [comment]
Sat på pause indtil vi ved mere om den specifikke struktur, og hvor der kan være bottlenecks i implementeringen.

**Comment by AxialDark** [comment]
This should be indirectly part of the #24 and if that is resolved this should as well

**Comment by AxialDark** [comment]
Related task #24 is done, therefore this has also been moved to done
